name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ngrok 
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Get ngrok path
        id: ngrok_path
        run: |
          echo "name=ngrok_path::$(which ngrok)"
      - name: Configure authtoken
        run: |
          ${{ steps.ngrok_path.outputs.ngrok_path }} authtoken 2dBbc8PBv0veCewDRjxg5HDxwjK_yTWc1vHk63PxkyLZyern

      - name: Run Streamlit Application
        id: streamlit
        run: |
          export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
          streamlit run Test_API.py &>/dev/null &
          ${{ steps.ngrok_path.outputs.ngrok_path }} http 8501 &

      - name: Display Ngrok URL
        run: |
          echo "Ngrok URL: ${{ steps.streamlit.outputs.ngrok_url }}"
