name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ngrok 
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok

      - name: Get ngrok path
        id: ngrok_path
        run: |
          echo "name=ngrok_path::$(which ngrok)"
      - name: Configure authtoken
        run: |
          ./ngrok authtoken 2dBbc8PBv0veCewDRjxg5HDxwjK_yTWc1vHk63PxkyLZyern

      - name: Run Streamlit Application
        id: streamlit
        run: |
          export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
          streamlit run Test_API.py &>/dev/null &
          ./ngrok http 8501 &

      - name: Display Ngrok URL
        run: |
          echo "Ngrok URL: ${{ steps.streamlit.outputs.ngrok_url }}"
