name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Streamlit Application
        id: streamlit
        run: |
          export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
          streamlit run Test_API.py &>/dev/null &
          ngrok_proc=$(ngrok http 8501)
          ngrok_url=$(echo "$ngrok_proc" | grep -Eo "https://.*\.ngrok\.io")
          echo "::set-output name=ngrok_url::$ngrok_url"
        shell: bash

      - name: Display Ngrok URL
        run: |
          echo "Ngrok URL: ${{ steps.streamlit.outputs.ngrok_url }}"
